/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BooksTable: typeof import('./components/BooksTable.vue')['default']
    ExamplesUi: typeof import('./components/system/ExamplesUi.vue')['default']
    FooterSection: typeof import('./components/FooterSection.vue')['default']
    HeroSearch: typeof import('./components/HeroSearch.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    ILucideBookmark: typeof import('~icons/lucide/bookmark')['default']
    ILucideDownload: typeof import('~icons/lucide/download')['default']
    ILucideEye: typeof import('~icons/lucide/eye')['default']
    ILucideGlobe: typeof import('~icons/lucide/globe')['default']
    ILucideInstagram: typeof import('~icons/lucide/instagram')['default']
    ILucideLink: typeof import('~icons/lucide/link')['default']
    ILucideQuote: typeof import('~icons/lucide/quote')['default']
    ILucideSearch: typeof import('~icons/lucide/search')['default']
    ILucideYoutube: typeof import('~icons/lucide/youtube')['default']
    ISimpleIconsX: typeof import('~icons/simple-icons/x')['default']
    NavigationBar: typeof import('./components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
